---
title: "final_project"
author: "Yu He"
date: "2023-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(deSolve)
```


```{r}
# Model function for TS-SIR
ts_sir_model <- function(time, state, parameters) {
  with(as.list(c(state, parameters)),{
    # rate of change
    dS <- mu * N + omega * R - beta * Cj * S * I / N - mu * S
    dI <- beta * Cj * S * I / N - gamma * I * rho - mu * I
    dR <- gamma * I * rho - mu * R - omega * R 
    
    # cumulative incidence
    dCumInc <- beta * S * I / N
    # return the rate of change
    list(c(dS, dI, dR, dCumInc))
  }) # end with(as.list...)
}

# Initial state values
N = 7395278 
I0 = 1211    # Initial infected population collected from the real data
S0 = (1/1.31) * N  # Approximate initial susceptible population
R0 =  N - I0 - S0      # Initial recovered population
cumInci0 = 104170	# Initial cumulative incidence collected from the real data

state <- c(S = S0, I = I0, R = R0, cumInci = cumInci0)

# Parameters for the model
# Cj is the contact ratio, rho is the reporting rate, obtained from the article's simulation.
# the reporduction number R0 is 1.31, 1.42, 1.08. R0 = beta/(mu + gamma). beta = R0 * (gamma + mu)
params_phase1 <- c(beta = 0.38, gamma = 1/3.5, mu = 1/85/365, omega = 2*pi/365, N = 7395278, Cj = 1, rho = 0.9)
params_phase2 <- c(beta = 0.41, gamma = 1/3.5, mu = 1/85/365, omega = 2*pi/365, N = 7395278, Cj = 0.73, rho = 0.8)  # Adjust Cj and rho for Phase 2
params_phase3 <- c(beta = 0.31, gamma = 1/3.5, mu = 1/85/365, omega = 2*pi/365, N = 7395278, Cj = 0.44, rho = 0.75)  # Adjust Cj and rho for Phase 3

# Time points for each phase
time_phase1 <- seq(0, 11, by = 1) # ordinary phase, before January 12, 2020
time_phase2 <- seq(12, 34, by = 1) # awareness phase, from January 12, 2020 to February 2, 2020
time_phase3 <- seq(34, 100, by = 1) # spreading phase, from February 2 , 2020 to February 23, 2020

# Solve the model for each phase
result_phase1 <- ode(y = state,
                     times = time_phase1,
                     func = ts_sir_model,
                     parms = params_phase1)

# Update initial state values for the next phase
initial_state_values <- result_phase1[nrow(result_phase1), 2:4]

state2 <- c(
  S = tail(result_phase1[, 'S'], 1),
  I = tail(result_phase1[, 'I'], 1),
  R = tail(result_phase1[, 'R'], 1),
  cumInci = tail(result_phase1[, 'cumInci'], 1)
)


result_phase2 <- ode(y = state2,
                     times = time_phase2,
                     func = ts_sir_model,
                     parms = params_phase2)

# Update initial state values for the next phase
initial_state_values <- result_phase2[nrow(result_phase2), 2:4]

state3 <- c(
  S = tail(result_phase2[, 'S'], 1),
  I = tail(result_phase2[, 'I'], 1),
  R = tail(result_phase2[, 'R'], 1),
  cumInci = tail(result_phase2[, 'cumInci'], 1)
)

result_phase3 <- ode(y = state3,
                     times = time_phase3,
                     func = ts_sir_model,
                     parms = params_phase3)

# Combine the results of all phases
result_all_phases <- rbind(result_phase1, result_phase2, result_phase3)


# SIR model without consider Covid-19 impact
times_no = seq(0, 100, by = 1)


result_no <- ode(y = state,
                     times = times_no,
                     func = ts_sir_model,
                     parms = params_phase1)


```


## import the real influenza data
```{r}
# real influenza cases from Jan 12 to Feb 23
para_est <- read_csv("dat0.csv") %>% 
  janitor::clean_names() %>% 
  subset(date < 43835) 

para_R0_est = para_est %>% 
  subset(date >= 43835 & date <= 43884)  

cumI = cumsum(para_est[,3])
```


# plot Number of Infected People vs the simulation with and without Covid-19 impact and real  data
```{r}
# plot the infectous
plot(result_all_phases[, "time"], result_all_phases[, "I"],
     type = "l",
     xlab = "Time (Days)",
     ylab = "Number of Infected People",
     main = "Infected People vs the simulation with and without Covid-19 impact and real data",
     col = "blue",
     ylim = c(0, 10000))

# plot the second line
lines(result_no[, "time"], result_no[, "I"],
      col = "red")

# add a legend to the plot
legend("topright", legend = c("With Covid-19 impact", "Without Covid-19 ipmact"),
       col = c("blue", "red"), lty = 1)

```


```{r}
# plot of the simulation without Covid-19 impact
times_no = seq(0, 1000, by = 1)

result_no <- ode(y = state,
                     times = times_no,
                     func = ts_sir_model,
                     parms = params_phase1)

plot(result_no[, "time"], result_no[, "I"],
     type = "l",
     xlab = "Time (Days)",
     ylab = "Number of Infected People",
     main = "Number of Infected People vs Time in the simulation without Covid-19 impact",
     col = "blue",
     ylim = c(0, 500000))
```



# the calculation to Rt - this is wrong need correction.
```{r}
# Calculate Rt for each time point
Rt_values <- params_phase1["R0"] * params_phase1["Cj"] * (result_all_phases[, "S"] / params_phase1["N"])

# Update Rt values for Phase 2
Rt_values[time_phase2] <- params_phase2["R0"] * params_phase2["Cj"] * (result_all_phases[time_phase2, "S"] / params_phase2["N"])

# Update Rt values for Phase 3
Rt_values[time_phase3] <- params_phase3["R0"] * params_phase3["Cj"] * (result_all_phases[time_phase3, "S"] / params_phase3["N"])

# Plot Rt vs time
plot(result_all_phases[, "time"], Rt_values,
     type = "l",
     xlab = "Time (Weeks)",
     ylab = "Effective Reproduction Number (Rt)",
     main = "Effective Reproduction Number (Rt) vs Time",
     col = "red",
     ylim = c(0, 100))

```










