---
title: "final_project"
author: "Yu He"
date: "2023-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(deSolve)
```


# Part 1, TS-SIR model set up
```{r}
# Model function for TS-SIR
ts_sir_model <- function(time, state, parameters) {
  with(as.list(c(state, parameters)),{
    # rate of change
    dS <- mu * N + omega * R - beta * Cj * S * I / N  - mu * S
    dI <- beta * Cj * S * I / N - gamma * I * rho - mu * I
    dR <- gamma * I * rho - mu * R - omega * R 
    
    # cumulative incidence
    dCumInc <- beta * Cj * S * I / N
    # return the rate of change
    list(c(dS, dI, dR, dCumInc))
  }) # end with(as.list...)
}

# Initial state values
N = 7395278 
I0 = 1211    # Initial infected population collected from the real data
S0 = (1/1.31) * N  # Approximate initial susceptible population
R0 =  N - I0 - S0      # Initial recovered population
cumInci0 = 4170	# Initial cumulative incidence collected from the real data

state <- c(S = S0, I = I0, R = R0, cumInci = cumInci0)

# Parameters for the model
# Cj is the contact ratio, rho is the reporting rate, obtained from the article's simulation.
# the reproduction number R0 is 1.31, 1.23, 1.08. R0 = beta/(mu + gamma). beta = R0 * (gamma + mu), 0.41. R0 = 1.31, 1.23, and 1.08 is provided by the article. 
params_phase1 <- c(beta = 0.37, gamma = 1/3.5, mu = 1/85/365, omega = 2*pi/365, N = 7395278, Cj = 1, rho = 0.9)
params_phase2 <- c(beta = 0.35, gamma = 1/3.5, mu = 1/85/365, omega = 2*pi/365, N = 7395278, Cj = 0.73, rho = 0.8)  # Adjust Cj and rho for Phase 2
params_phase3 <- c(beta = 0.31, gamma = 1/3.5, mu = 1/3.5, omega = 2*pi/365, N = 7395278, Cj = 0.44, rho = 0.75)  # Adjust Cj and rho for Phase 3

# Time points for each phase
time_phase1 <- seq(0, 11, by = 1) # ordinary phase, before January 12, 2020
time_phase2 <- seq(12, 34, by = 1) # awareness phase, from January 12, 2020 to February 2, 2020
time_phase3 <- seq(34, 100, by = 1) # spreading phase, after February 2 , 2020 

# Solve the model for each phase
result_phase1 <- ode(y = state,
                     times = time_phase1,
                     func = ts_sir_model,
                     parms = params_phase1)

# Update initial state values for the next phase
initial_state_values <- result_phase1[nrow(result_phase1), 2:4]

state2 <- c(
  S = tail(result_phase1[, 'S'], 1),
  I = tail(result_phase1[, 'I'], 1),
  R = tail(result_phase1[, 'R'], 1),
  cumInci = tail(result_phase1[, 'cumInci'], 1)
)


result_phase2 <- ode(y = state2,
                     times = time_phase2,
                     func = ts_sir_model,
                     parms = params_phase2)

# Update initial state values for the next phase
initial_state_values <- result_phase2[nrow(result_phase2), 2:4]

state3 <- c(
  S = tail(result_phase2[, 'S'], 1),
  I = tail(result_phase2[, 'I'], 1),
  R = tail(result_phase2[, 'R'], 1),
  cumInci = tail(result_phase2[, 'cumInci'], 1)
)

result_phase3 <- ode(y = state3,
                     times = time_phase3,
                     func = ts_sir_model,
                     parms = params_phase3)

# Combine the results of all phases
result_all_phases <- rbind(result_phase1, result_phase2, result_phase3)


# SIR model without consider Covid-19 impact
times_no = seq(0, 100, by = 1)


result_no <- ode(y = state,
                     times = times_no,
                     func = ts_sir_model,
                     parms = params_phase1)


```


# Part 2, results plot 
## import the real influenza data
```{r}
# real influenza cases from Jan 12 to Feb 23
para_est <- read_csv("dat0.csv") %>% 
  janitor::clean_names() %>% 
  subset(date < 43830) 

cumI = cumsum(para_est[,3])


# Define the reference date
reference_date <- as.Date("2020-01-01")

para_R0_est = read_csv("dat0.csv") %>% 
  subset(date >= 43830 & date <= 43884) %>%
  janitor::clean_names() %>% 
  mutate(
    date = reference_date + (date - 43835)
  ) %>% 
  select(date, real_flu_case)

```


## plot Number of Infected People vs the simulation with and without Covid-19 impact and real data
```{r}
result_all_phases = as.data.frame(result_all_phases)
result_no = as.data.frame(result_no)


# Convert time values to dates
start_date <- as.Date("2020-01-01")
result_all_phases$date <- start_date + result_all_phases$time
result_no$date <- start_date + result_no$time

# Combine data frames
result_all_phases$Scenario <- "With Covid-19 impact"
result_no$Scenario <- "Without Covid-19 impact"
data <- rbind(result_all_phases, result_no)

# Create the combined plot using ggplot2
ggplot() +
  geom_line(data = data, aes(x = date, y = I, color = Scenario)) +
  geom_bar(data = para_R0_est, aes(x = date, y = real_flu_case, fill = "Real data"), stat = "identity", alpha = 0.5, inherit.aes = FALSE) +
  geom_text(data = para_R0_est, aes(x = date, y = real_flu_case, label = real_flu_case), vjust = -0.5, size = 3.5, inherit.aes = FALSE) +
  labs(x = "Date", y = "Number of Cases",
       title = "Infected People vs time with and without Covid-19 impact and real data") +
  scale_color_manual(name = "Scenario", values = c("blue", "red"), labels = c("With Covid-19 impact", "Without Covid-19 impact")) +
  scale_fill_manual(name = "", values = "steelblue", labels = "Real data") +
  ylim(0, 10000) +
  theme_minimal() +
  theme(legend.position = "top",
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title = element_text(size = 12, face = "bold"),
        plot.title = element_text(size = 14, face = "bold", hjust = 0.5)) +
  guides(fill = guide_legend(override.aes = list(color = NA))) +
  scale_x_date(date_labels = "%Y-%m-%d", date_breaks = "7 days") +
  geom_vline(xintercept = as.numeric(as.Date("2020-01-12")), linetype = "dashed", color = "grey") +
  geom_vline(xintercept = as.numeric(as.Date("2020-02-02")), linetype = "dashed", color = "grey")

```


## plot the infectous %

```{r}
# Convert time values to dates
start_date <- as.Date("2020-01-01")
result_all_phases$date <- start_date + result_all_phases$time
result_no$date <- start_date + result_no$time

# Calculate percentage of infectious individuals
# Replace with the total population of your simulation
result_all_phases$Pct_I <- result_all_phases$I / N * 100
result_no$Pct_I <- result_no$I / N * 100

# Combine data frames
result_all_phases$Scenario <- "With Covid-19 impact"
result_no$Scenario <- "Without Covid-19 impact"
data <- rbind(result_all_phases, result_no)

# Create the plot using ggplot2
ggplot(data, aes(x = date, y = Pct_I, color = Scenario)) +
  geom_line() +
  labs(x = "Date", y = "Percentage of Infectious Individuals",
       title = "Percentage of Infectious Individuals vs Date") +
  scale_color_manual(values = c("blue", "red")) +
  ylim(0, 0.1) +
  theme_minimal() +
  theme(legend.position = "top",
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_date(date_labels = "%Y-%m-%d", date_breaks = "7 days") +
  geom_vline(xintercept = as.numeric(as.Date("2020-01-12")), linetype = "dashed", color = "grey") +
  geom_vline(xintercept = as.numeric(as.Date("2020-02-02")), linetype = "dashed", color = "grey")
```


## plot of the simulation without Covid-19 impact
```{r}
# plot of the simulation without Covid-19 impact
times_no = seq(0, 1000, by = 1)

result_no <- ode(y = state,
                     times = times_no,
                     func = ts_sir_model,
                     parms = params_phase1)

plot(result_no[, "time"], result_no[, "I"],
     type = "l",
     xlab = "Time (Days)",
     ylab = "Number of Infected People",
     main = "Number of Infectious vs Time without Covid-19 impact",
     col = "blue",
     ylim = c(0, 700000))

# % infectious
plot(result_no[, "time"], result_no[, "I"] / N *100,
     type = "l",
     xlab = "Time (Days)",
     ylab = "% Infected People",
     main = "% Infectious vs Time without Covid-19 impact",
     col = "blue",
     ylim = c(0, 8))
```












