---
title: "ts_sir_model"
author: "Yu He"
date: "2023-04-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Load libraries
library(deSolve)
library(tidyverse)
```



```{r}

# Define the TS-SIR model with demography
TS_SIR_model_demography <- function(t, state, parameters) {
  with(as.list(c(state, parameters)), {
    N <- S + I + R

    if (t < t1) {
      beta <- beta1 * C1
      PHIj <- (1 - C1) * 100
    } else if (t < t2) {
      beta <- beta2 * C2
      PHIj <- (1 - C2) * 100
    } else {
      beta <- beta3 * C3
      PHIj <- (1 - C3) * 100
    }

    dS <- mu * N - beta * S * I / N - mu * S
    dI <- beta * S * I / N - gamma * I - mu * I
    dR <- gamma * I - mu * R
    dCumInc <- beta * S * I / N

    return(list(c(dS, dI, dR, dCumInc, PHIj)))
  })
}

# Initial conditions
N <- 7395278
I0 <- 1
S0 <- N - I0
R0 <- 1.37
CumInc0 <- 0
PHIj0 <- 0
initial_state <- c(S = S0, I = I0, R = R0, CumInc = CumInc0, PHIj = PHIj0)

# Time points
time_phase1 <- seq(0, 11, by = 1)
time_phase2 <- seq(12, 34, by = 1)
time_phase3 <- seq(34, 55, by = 1)
times <- c(time_phase1, time_phase2, time_phase3)

# Model parameters
rho1 <- 0.0065
rho2 <- 0.0057
rho3 <- 0.0022

parameters <- c(
  beta1 = 0.5, 
  beta2 = 0.58, 
  beta3 = 0.45, 
  C1 = 1, 
  C2 = 1 - 0.174, # Update C2 based on the effects of wearing face masks and avoiding crowded places
  C3 = 1 - 0.329, 
  gamma = 0.1, 
  t1 = 12, 
  t2 = 34,
  mu = 1/(70*365) # Birth and death rate, adjust as needed
)

# Run the updated TS-SIR model with demography
output_demography <- ode(y = initial_state, times = times, func = TS_SIR_model_demography, parms = parameters)

# Display the results
output_demography_df <- data.frame(output_demography)
colnames(output_demography_df) <- c("time", "S", "I", "R", "CumInc", "PHIj")
print(output_demography_df)

# ... (Plotting code from the previous answer) ...


# Plot the results
ggplot(output_df, aes(x = time)) +
  geom_line(aes(y = I, color = "Infectious")) +
  geom_line(aes(y = CumInc, color = "Cumulative Incidence")) +
  scale_y_continuous(name = "Number of Individuals") +
  xlab("Time") +
  labs(color = "Variables") +
  theme_minimal()
```



```{r}
beta1 = 0.5 
beta2 = 0.58
beta3 = 0.45 
mu = 1/(70*365)
  t1 = 12 
  t2 = 34
# Calculate R0 at each time point
R0_values <- with(output_demography_df, beta1 * C1 * S / (gamma + mu) +
                    ifelse(time < t1, 0, beta2 * C2 * S / (gamma + mu)) +
                    ifelse(time < t2, 0, beta3 * C3 * S / (gamma + mu)))

# Plot R0 vs time
plot(output_demography_df$time, R0_values, type = "l",
     xlab = "Time", ylab = "Effective Reproduction Number (R0)",
     main = "R0 vs Time")

```



```{r}
# Calculate Rt values for each time step
R0 <- 1.37 # placeholder value, adjust as needed
Rt_values <- c()
for (t in times) {
  if (t < parameters["t1"]) {
    Rt <- R0 * parameters["C1"]
  } else if (t < parameters["t2"]) {
    Rt <- R0 * parameters["C2"]
  } else {
    Rt <- R0 * parameters["C3"]
  }
  Rt_values <- c(Rt_values, Rt)
}

# Add Rt values to the output data frame
output_df$Rt <- Rt_values

# Plot Rt vs. time
ggplot(output_df, aes(x = time, y = Rt)) +
  geom_line() +
  labs(title = "Effective Reproduction Number (Rt) vs. Time",
       x = "Time",
       y = "Rt") +
  theme_minimal()

# Plot infectious vs. time
ggplot(output_df, aes(x = time, y = I)) +
  geom_line() +
  labs(title = "Infectious vs. Time",
       x = "Time",
       y = "Infectious") +
  theme_minimal()
```



```{r}
# Define the time points for each phase
time_phase1 <- 1:30
time_phase2 <- 31:60
time_phase3 <- 61:90

# Define the parameter values for each phase
beta1 <- 0.4
beta2 <- 0.3
beta3 <- 0.2
gamma <- 0.1
w <- 0.01
omega <- 0.05
rho1 <- 0.1
rho2 <- 0.2
rho3 <- 0.3
C1 <- 0.8
C2 <- 0.6
C3 <- 0.4
R0 <- 2.5

# Define the initial conditions
S0 <- 990
I0 <- 10
R0 <- 0
Rw0 <- 0

# Define the system of ODEs
ts_sir <- function(t, y, params) {
  with(as.list(c(params, y)), {
    # Define the contact ratio and effective reproduction number for the current time
    if (t %in% time_phase1) {
      C <- C1
      Rt <- R0 * C * (S/N)
    } else if (t %in% time_phase2) {
      C <- C2
      Rt <- R0 * C * (S/N)
    } else {
      C <- C3
      Rt <- R0 * C * (S/N)
    }
    
    # Define the system of ODEs
    dS <- -beta * C * S * I / N
    dI <- beta * C * S * I / N - gamma * I
    dR <- gamma * I - w * R
    dRw <- w * R - omega * Rw
    
    # Define the reported incidence at the current time
    Y <- rho * (Sprev - S)
    
    # Return the derivatives as a list
    list(c(dS, dI, dR, dRw), Y)
  })
}

# Define the time grid
t_grid <- 1:90

# Simulate the model using the deSolve package
library(deSolve)

params <- list(beta = beta1, gamma = gamma, w = w, omega = omega, rho = rho1, C = C1, N = S0 + I0 + R0 + Rw0, R0 = R0)
y0 <- c(S = S0, I = I0, R = R0, Rw = Rw0)
out <- ode(y = y0, times = t_grid, func = ts_sir, parms = params)

# Plot the results
plot(out, xlab = "Time", ylab = "Number of individuals", main = "TS-SIR model with waning immunity")
legend("topright", c("S", "I", "R", "Rw"), col = 1:4, lty = 1:4)

```


```{r}
# Parameter estimate
para_est <- read_csv("dat0.csv") %>% 
  janitor::clean_names() 

cumI = cumsum(para_est[,3])

para_R0_est = para_est %>% 
  subset(date >= 43835 & date <= 43884)  

cumI_R0 = cumsum(para_R0_est[,3])

# Fit to the data during the first 7 days:
D = 3; # set the generation time to 3 days
Ndays = 11;  # ADJUST THE NUMBER OF DAYS INCLUDED IN THE FIT HERE
tm1 = 1:Ndays;
fit1 = lm(log(cumI_R0[1:Ndays]) ~ tm1)
summary(fit1)

# compute R0 based on the model-fit
R = 1 + fit1$coefficients[2]*D   # slope: fit1$coefficients[2]

cumI_R0[1:Ndays]
```



